### Get all books
GET http://localhost:3000/api/books

###

### Create a new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "id": 4,
  "title": "The Shivam Gatsby",
  "author": "F. Scott Fitzgerald"
}

###

### Update a book
PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
  "title": "Updated Book Title",
  "author": "Updated Author"
}

###

### Delete a book
DELETE http://localhost:3000/api/books/1

###
